### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

Creating Numpy Arrays

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
# 2D
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [5]:
#3D
c= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# dtype {we can change the dtype of elements}
d = np.array([10,20,30], dtype = bool)
print( d)

[ True  True  True]


In [7]:
# np.arange { just like range in python- here we can aslo set range of Narray}
e = np.arange(1,11) # 1 is include and 11 is exclude
print(e)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
# with reshape {using arange function, then we can set shape of Narray}
f = np.arange(1,11).reshape(2,5)
print(f)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
# np.ones and np.zeros
#{the aim of using one and zero is to initialize Narray}
g = np.ones((1,5))
print(g)

[[1. 1. 1. 1. 1.]]


In [10]:
h = np.zeros((1,5))
print(h)

[[0. 0. 0. 0. 0.]]


In [11]:
# np.random {this will give you random numbers btw 0 and 1}
np.random.random((3,4))

array([[0.88360777, 0.61217411, 0.45877027, 0.36867008],
       [0.62004369, 0.12154216, 0.80652699, 0.98739052],
       [0.5313966 , 0.09383884, 0.53770917, 0.219893  ]])

In [12]:
# np.linspace {linear space}
i = np.linspace(-10,10,10) # -10 is starting number,middle 10 is range, last 10 is elements
print(i)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [13]:
# np.identity {in diagnals all elements will be 1}
j  = np.identity(3)
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#Attributes

In [37]:
k1 = np.arange(12,dtype=int)
k2 = np.arange(12,dtype=int).reshape(4,3)
k3 = np.arange(8,dtype=int).reshape(2,2,2)


In [38]:
#ndim {used for finding the dimension of Narray}
k3.ndim

3

In [39]:
# shape { it show the elements size}
k2.shape

(4, 3)

In [40]:
# size {size means how it take space in bytes}
print(k3.size)

8


In [41]:
# itemsize
k1.itemsize

8

In [42]:
# dtype
k1.dtype

dtype('int64')

Changing Datatype

In [43]:
#sometime arrays accupies lots of space, to save it we change type of array
k1.astype(np.int32)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)

Array Operations
we can perform many operation like arithmetic, scalar, vector

In [44]:
a

array([1, 2, 3])

In [45]:
#scalar operation {means -,+,*,/ a number with array}
a**2

array([1, 4, 9])

In [46]:
#vector {lets suppose we have 2D array and want to add 2 with each elements the we use vectors}
b+2

array([[3, 4],
       [5, 6]])

Array Functions

In [47]:
l = np.random.random((3,3))
l = np.round(l*100) # as random give number btw 0 and 1 , so we multiply each number by 100
l

array([[64., 45., 22.],
       [ 1., 80., 71.],
       [80., 78., 18.]])

In [48]:
#min/max/sum/prod
np.max(l)

np.float64(80.0)

In [49]:
# mean/median/std/var
np.std(l)

np.float64(28.763402673072832)

In [50]:
# dot product {when we want to multiple two array of same order}
# the rules of maths for dot product will also apply here

m = np.arange(12).reshape(3,4)
n = np.arange(10,22).reshape(4,3)
m.dot(n)

array([[102, 108, 114],
       [334, 356, 378],
       [566, 604, 642]])

In [51]:
# round/floor/ceil
np.round(b)

array([[1, 2],
       [3, 4]])

Indexing and Slicing

In [52]:
k1 # indexing in vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
k1[6] # same like array index in python, array start from zero. -1 strat array from reverse.

np.int64(6)

In [54]:
k2 # indexing in 2D {As in 2D we have rows and cols , the first number will for row and second for cols}

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
k2[1,2] # its for searching a specific number in matrix

np.int64(5)

for 2D how slicong works

In [60]:
#if i want to extarct the first two rows then I will use slicing concept
k2[0:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
#for last two rows
k2[2:]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [62]:
#if i want to get 0,1 & 3,4
k2[0:2,0:2] # here first zero for rows, and two for row-range (means how many rows) and second 0 for cols and again two for cols range

array([[0, 1],
       [3, 4]])

In [63]:
# for 7,8 & 8,10
k2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [64]:
k2[2:,1:]

array([[ 7,  8],
       [10, 11]])

In [66]:
# for 0,2 & 9 , 11
k2[0::3,0::2]

array([[ 0,  2],
       [ 9, 11]])

In [72]:
# for 3 & 5 only
k2[1,0::2]

array([3, 5])

for 3D array how slicing works

In [75]:
k3= np.arange(27).reshape(3,3,3)
k3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [76]:
#if i want to print the middle 2D array, then-
k3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [79]:
#for first and last array
k3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [80]:
#extract from first array second row
k3[0,1,0:]

array([3, 4, 5])

In [81]:
# extract from 2 3D array middle cols
k3[1,:,1]

array([10, 13, 16])

Iterating ( means loop )

In [82]:
k1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
for i in k1:
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [84]:
#using 2D
k2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [85]:
for i in k2:
  print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [86]:
#3D
k3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [87]:
for i in k3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


Reshaping ( reshaping, transpose, and ravel )

In [88]:
# we already talked about reshape, now lwts talk about transpose and revel

In [89]:
#transpose----> change row in to cols
k2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [91]:
np.transpose(k2)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [92]:
# for short write only T
k2.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [93]:
# ravel is used to convert any ndimension array into vector
k2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
k3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking ( means combining two array of same order, horizontally and verticallly

In [95]:
k2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [106]:
k4= np.arange(12,24).reshape(4,3)

In [107]:
k4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [110]:
#horizontally
np.hstack((k2,k4))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17],
       [ 6,  7,  8, 18, 19, 20],
       [ 9, 10, 11, 21, 22, 23]])

In [111]:
# vertically
np.vstack((k2,k4))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])