In [15]:
import numpy as np

In [16]:
a=np.array((12,324,65,87,765,456,98,2345,1))
a

array([  12,  324,   65,   87,  765,  456,   98, 2345,    1])

In [17]:
#sorting
a.sort()
a

array([   1,   12,   65,   87,   98,  324,  456,  765, 2345])

In [18]:
#Append
np.append(a,100)
a

array([   1,   12,   65,   87,   98,  324,  456,  765, 2345])

In [19]:
b = np.random.randint(1,50,10)
b

array([32, 19, 22, 39,  9, 49, 49, 43, 31, 18])

In [20]:
#concatenateing .....> combining
np.concatenate((a,b))

array([   1,   12,   65,   87,   98,  324,  456,  765, 2345,   32,   19,
         22,   39,    9,   49,   49,   43,   31,   18])

In [21]:
#unique for getting only unique values
np.unique(a)

array([   1,   12,   65,   87,   98,  324,  456,  765, 2345])

In [22]:
#expand_dims-----> used for changing dimension of an array
#let suppose we have a single row- we can change into 1 row and many cols
#kike
a

array([   1,   12,   65,   87,   98,  324,  456,  765, 2345])

In [58]:
# 9 rows and 1 cols
np.expand_dims(a,axis=1).shape

(9, 1)

In [59]:
#where -----> it retuen the indices of only those values, where condition is satisfied
np.where(a>100) # checing for show only those indices whose values are greater then 50

(array([5, 6, 7, 8]),)

In [60]:
# argmax | argmin ----> show only those indix whose value is graeter or smaller
np.argmax(a)

np.int64(8)

In [61]:
b

array([32, 19, 22, 39,  9, 49, 49, 43, 31, 18])

In [62]:
#arg_min for smallest value
np.argmin(b)

np.int64(4)

In [63]:
#cumsum----> means for commulative sum, find sum of all ele of array
c = np.arange(12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:

np.cumsum(c)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [65]:
np.expand_dims(b,axis=0).shape

(1, 10)

In [66]:
#cumprod----> cummulative product
np.cumprod(b)

array([             32,             608,           13376,          521664,
               4694976,       230053824,     11272637376,    484723407168,
        15026425622208, 270475661199744])

In [67]:
#percentile is used to compute the nth percentile of given data
#in simple if i give 50 in array, am cheching how many number are back from 50
np.percentile(b,100)

np.float64(49.0)

In [70]:
b

array([32, 19, 22, 39,  9, 49, 49, 43, 31, 18])

In [71]:
#histogram # which show how many item sre under listed in one bin
import matplotlib.pyplot as plt
np.histogram(b,bins=[10,20,30,40,50])

(array([2, 1, 3, 3]), array([10, 20, 30, 40, 50]))

In [72]:
#isin ----> checking whether the number is available inside the array or not
np.isin(b,12)

array([False, False, False, False, False, False, False, False, False,
       False])

In [73]:
#flip -----> working like transpose of matrics
np.flip(c)

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [74]:
#put ----> adding new in array
np.put(b,2,100) # in array named "b" index 2 put 100

In [75]:
b

array([ 32,  19, 100,  39,   9,  49,  49,  43,  31,  18])

In [78]:
# deleting
np.delete(b,2) # array, and index of specific element

array([32, 19, 39,  9, 49, 49, 43, 31, 18])

In [79]:
#union1d----> just like maths make a new array of ele without duplication
e = np.array((1,2,3,4,5,6,7,5,4,3,2))
f = np.array((11,12,13,4,5,16,7,5,41,3,12))
np.union1d(e,f)

array([ 1,  2,  3,  4,  5,  6,  7, 11, 12, 13, 16, 41])

In [80]:
# intersect1d ----> intersect means take only common
e = np.array((1,2,3,4,5,6,7,5,4,3,2))
f = np.array((11,12,13,4,5,16,7,5,41,3,12))
np.intersect1d(e,f)

array([3, 4, 5, 7])

In [82]:
# setdiff1d -----> set didderence means select only those value which are
# avaible in set e but not in f
np.setdiff1d(e,f)

array([1, 2, 6])

In [85]:
# clip ----> used for cutting the array based on condition to keep only those
# value which come in range - means you set minimum and aximum range for array
np.clip(b,a_min=30, a_max=50)

array([32, 30, 50, 39, 30, 49, 49, 43, 31, 30])